### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


In [1]:
import numpy as np

###### 1. Write a NumPy program to find the missing data in a given array.

In [ ]:
### code here

In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [9]:
arr = np.array([[[ 3,  2, np.nan,  1,],
                 [10, 12, 10,  9,],
                 [ 5, np.nan,  1, np.nan]]])
print(f'Orgnal array:\n {arr}\n Find the missing data of the said array:\n{np.isnan(arr)}')

Orgnal array:
 [[[ 3.  2. nan  1.]
  [10. 12. 10.  9.]
  [ 5. nan  1. nan]]]
 Find the missing data of the said array:
[[[False False  True False]
  [False False False False]
  [False  True False  True]]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [ ]:
### code here 

In [10]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([1, 2, 3, 4, 5])
are_equal = np.array_equal(array1, array2)

if are_equal:
    print("The two arrays are equal element-wise.")
else:
    print("The two arrays are not equal element-wise.")

The two arrays are equal element-wise.


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [ ]:
## code here

In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [ ]:
#ANS

In [5]:
ar = np.arange(0,16).reshape(4,4)
print(f'Original array:\n{ar}\n New array after swapping first and last rows of the said array:\n{ar[-1::-1]}')


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
 New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [ ]:
#### code here

In [22]:
a = [1,2,3,4,5]
b=(0,6,7,8,9)

arr1 = np.array(a)
arr2 = np.array(b)

arr1  , arr2

(array([1, 2, 3, 4, 5]), array([0, 6, 7, 8, 9]))

###### 5. Write a NumPy program to find common values between two arrays.

In [ ]:
### code here

In [28]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([2,4,1,6,8])

common_val1=np.intersect1d(a1,a2)

common_val1

array([1, 2, 4])

###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [ ]:
### code here

In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [ ]:
#ANS

In [30]:
arr1 =np.array([1,2,3,4,5,6])
print(f'Reshape 3x2:\n{(arr1.reshape(3,2))}\n Reshape 2x3:\n{arr1.reshape(2,3)}')

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
 Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [ ]:
### code here

In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
#ANS

In [4]:
a=np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print(f"Original array:\n{a}\nFrequency of unique values of the said array:\n{np.array(np.unique(a,return_counts=True))}")

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [ ]:
### code here

In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
#ANS

In [5]:
a=np.array([[0,0,0],[1,2,3],[4,5,6]])
b=np.array([10,11,12])
print(f"Original arrays:\nArray-1\n{a}\nArray-2\n{b}\nNew Array:\n{a+b}")

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]
New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [ ]:
### code here

In [ ]:
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


In [ ]:
#ANS

In [6]:
a=np.arange(0,16).reshape(4,4)
print(f"Original array:{a}\n\nExtracted data: Second row\n{a[1,:]}")

Original array:[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [ ]:
## code here

In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


In [7]:
a=np.arange(0,16).reshape(4,4)
print(f"Original array:{a}\n\nExtracted data: Second row\n{a[0:2,2:]}")

Original array:[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [ ]:
### code here

In [11]:
yesterday = np.datetime64('today','D') - np.timedelta64(1, 'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1, 'D')
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-01-14
Today: 2024-01-15
Tomorrow: 2024-01-16


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [ ]:
## code here

In [ ]:
## sample output

First Monday in May 2017:
2017-05-01


In [14]:
import numpy as np

# Specify the date for May 2017
date_in_may_2017 = np.datetime64('2017-05-01')

# Find the first Monday in May 2017
first_monday_in_may_2017 = np.busday_offset(date_in_may_2017, 0, roll='forward', weekmask='Mon')

print("The first Monday in May 2017 is on:", first_monday_in_may_2017)


The first Monday in May 2017 is on: 2017-05-01
